import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import MyMenu from "@/components/molecules/my-menu/my-menu";
import ApplicationProvider from "@/context/application.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApplicationProvider>
          <>
            <MyMenu />
            {children}
          </>
        </ApplicationProvider>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" />
      </body>
    </html>
  );
}
