import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import MyMenu from "@/components/molecules/my-menu/my-menu";
import ApplicationProvider from "@/context/application.provider";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutParams {
  locale: string;
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: LayoutParams;
}) {
  let translations;
  try {
    translations = (await import(`../../languages/${params.locale}.json`))
      .default;
  } catch (error) {
    translations = (await import(`../../languages/en.json`)).default;
  }

  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider locale={params.locale} messages={translations}>
          <ApplicationProvider>
            <>
              <MyMenu />
              {children}
            </>
          </ApplicationProvider>
        </NextIntlClientProvider>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" />
      </body>
    </html>
  );
}
